Escape char ` in bash or it tries to execute command (thx to r3b3lu for report)

diff --git a/trunk/verlihub/scripts/vh_install b/trunk/verlihub/scripts/vh_install
--- a/trunk/verlihub/scripts/vh_install
+++ b/trunk/verlihub/scripts/vh_install
@@ -90,7 +90,7 @@ function CreateTables
 	echo Wait few seconds..
 	getMySQLSocket
 	export "MYSQL_UNIX_PORT=$SOCKET"
-	VERLIHUB_CFG=$cfg_dir $bindir/verlihub 22 &>/dev/null &
+	VERLIHUB_CFG=$cfg_dir $bindir/verlihub 22 &>$cfg_dir/install_log &
 	vh_pid=$!
 	sleep 5
 	kill -9 $vh_pid &>/dev/null
@@ -166,7 +166,7 @@ if $db_create ; then
 	echo
 
 	echo "You'll be now promted by $MYSQL client for password of $mysql_root@$mysql_host"
-	$MYSQL -h "$mysql_host" -u "$mysql_root" -p -e "CREATE DATABASE IF NOT EXISTS $mysql_data; GRANT ALL ON $mysql_data.* to $mysql_user@$mysql_this_host identified by '$mysql_pass'"
+	$MYSQL -h "$mysql_host" -u "$mysql_root" -p -e "CREATE DATABASE IF NOT EXISTS \`$mysql_data\`; GRANT ALL ON \`$mysql_data\`.* to '$mysql_user'@'$mysql_this_host' identified by '$mysql_pass'"
 	Sep
 
 	TestDB "$mysql_host" "$mysql_user" "$mysql_pass" "$mysql_data" && db_exists=true || db_exists=false
@@ -256,7 +256,7 @@ fi
 
 export VERLIHUB_CFG=$cfg_dir
 
-CreateTables || die "ERROR: verlihub's $MYSQL tables do not exist, cannot continue installation";
+CreateTables || die "ERROR: verlihub's $MYSQL tables do not exist, cannot continue installation. Please check $cfg_dir/install_log file for more info";
 	
 
 Sep
@@ -268,7 +268,7 @@ setup_info_ok=false
 
 until $setup_info_ok; do
 	Sep
-	echo "Try to not put many special characters, you'll be able to put some laer"
+	echo "Try to not put many special characters, you'll be able to put some later"
 	echo
 	hostname=`hostname`
 	vh_master=`GetVar "" "[SU]$USER" "Give me your DC hub master nickname.."`
