[scripts/vh_migration_0.9.8eto1.0.in] Added help function and deletion of old scripts

diff --git a/scripts/vh_migration_0.9.8eto1.0.in b/scripts/vh_migration_0.9.8eto1.0.in
--- a/scripts/vh_migration_0.9.8eto1.0.in
+++ b/scripts/vh_migration_0.9.8eto1.0.in
@@ -17,84 +17,121 @@ function _delete_lang_var() #var
 	fi
 }
 
+function help_me()
+{
+	echo_s "$SCRIPT\n" $BOLD
+	echo "This is a migration script for Verlihub 1.0, usage:"
+	echo_s "   --clean" $RED && echo -e "\t\t\t\tClean directory from old binary/script files"
+	echo_s "   --hub" $RED && echo -e "\t<path_to_dbconfig> \tUpdate hu database with the given dbconfig path"
+	echo_s "   --help" $RED && echo -e "\t\t\t\tShow this help"
+	echo ""
+}
 
-echo_s "-- Welcome to verliHub migration script to version 0.9.9a\n" $RED_BOLD
-echo "-- In order to make migration you need to specify the verlihub config folder to get database information"
+function migrate_hub() #path_to_dbconfig
+{
 
-# Select path where to put verlihub config file
-IS_CHOOSEN_FOLDER_OK=false
-until $IS_CHOOSEN_FOLDER_OK;
-do
-	echo_s "\t[1] " $BOLD && echo "/etc/verlihub"
-	echo_s "\t[2] " $BOLD && echo "$HOME.verlihub"
-	echo_s "\t[3] " $BOLD && echo "$PREFIX/etc/verlihub"
-	echo_s "\t[4] " $BOLD && echo "Other, choose path where put config file"
-
-	CHOOSEN_FOLDER=$(ask "Select number")
-
-	# Get selected folder
-	case $CHOOSEN_FOLDER in
-		"1") CHOOSEN_FOLDER="/etc/verlihub/";;
-		"2") CHOOSEN_FOLDER="$HOME.verlihub/";;
-		"3") CHOOSEN_FOLDER="$PREFIX/etc/verlihub/";;
-		"4") CHOOSEN_FOLDER=$(ask "Type complete path");
-	esac
-
-	if set_path $CHOOSEN_FOLDER ; then
-		IS_CHOOSEN_FOLDER_OK=true
+	# Check config directory
+	if [ "_$1" != "_" ]; then
+		if ! set_path $1 ; then
+			exit 1;
+		fi
 	else
-	echo -e "\nOk, let's try again"
+		echo_s "-- Please specify a config folder\n" $RED
+		exit 1;
 	fi
-done
 
-echo "-- You verlihub config folder is '$CONFIG_DIR'"
+	echo_s "-- Welcome to VerliHub migration script to version 0.9.9a for your hub\n" $RED_BOLD
+	echo "-- You verlihub config folder is '$CONFIG_DIR'"
 
-if $(yes_or_no "Do you want to continue with migration?") ; then
-	echo "-- Deleting ban message variables"
-	BAN_MESSAGES=(ban_reason ban_remaining ban_expired ban_for ban_permanently ban_type ban_removed ban_by ban_types_nickip ban_types_ip ban_types_nick ban_types_iprange ban_types_host1 ban_types_host2 ban_types_host3 ban_types_share ban_types_email ban_types_prefix ban_types_rhost1)
-	for VAR in ${BAN_MESSAGES[@]}; do
-		_delete_lang_var $VAR
-	done
-	sleep 2
+	if $(yes_or_no "Do you want to continue with hub migration?") ; then
+		echo "-- Deleting ban message variables"
+		BAN_MESSAGES=(ban_reason ban_remaining ban_expired ban_for ban_permanently ban_type ban_removed ban_by ban_types_nickip ban_types_ip ban_types_nick ban_types_iprange ban_types_host1 ban_types_host2 ban_types_host3 ban_types_share ban_types_email ban_types_prefix ban_types_rhost1)
+		for VAR in ${BAN_MESSAGES[@]}; do
+			_delete_lang_var $VAR
+		done
+		sleep 2
 
-	echo "-- Deleting timeout message variables"
-	TIMEOUT_MESSAGES=(timeout_key timeout_nick timeout_login timeout_myinfo timeout_flush timeout_setpass)
-	for VAR in ${TIMEOUT_MESSAGES[@]}; do
-		_delete_lang_var $VAR
-	done
-	sleep 2
+		echo "-- Deleting timeout message variables"
+		TIMEOUT_MESSAGES=(timeout_key timeout_nick timeout_login timeout_myinfo timeout_flush timeout_setpass)
+		for VAR in ${TIMEOUT_MESSAGES[@]}; do
+			_delete_lang_var $VAR
+		done
+		sleep 2
 	
-	echo "-- Deleting tag_min_version and tag_max_version variables"
-	CLIENTS=(plusplus dcgui odc dc dcpro strongdc idc zdc apexdc zion)
-	for VAR in ${CLIENTS[@]}; do
-		_delete_config_var "tag_min_version_$VAR"
-		_delete_config_var "tag_max_version_$VAR"
-	done
-	sleep 2
+		echo "-- Deleting tag_min_version and tag_max_version variables"
+		CLIENTS=(plusplus dcgui odc dc dcpro strongdc idc zdc apexdc zion)
+		for VAR in ${CLIENTS[@]}; do
+			_delete_config_var "tag_min_version_$VAR"
+			_delete_config_var "tag_max_version_$VAR"
+		done
+		sleep 2
 
-	echo "-- Deleting other variables"
-	OTHER_MESSAGES=(save_lang chat_msg_long chat_msg_lines pwd_cannot pwd_can pwd_min pwd_success pwd_set_error pwd_setup ip nick user host ip_range because op type not_in_userlist error success wrong_dc_tag tag_max_hubs tag_max_slots tag_min_slots tag_max_hs_ratio tag_min_limit tag_min_ls_ratio tag_no_sock msg_downgrade msg_upgrade msg_topic_set msg_topic_reset autoreg_nick_prefix autoreg_already_reg autoreg_success autoreg_error timeout_any operation_timeout msg_chat_onoff msg_change_pwd msg_banned msg_hub_full msg_nick_prefix msg_downgrade msg_upgrade msg_replace_ban login_share_min login_share_max autoreg_min_share search_share_min ctm_share_min max_attempts_threshold)
-	for VAR in ${OTHER_MESSAGES[@]}; do
-		_delete_lang_var $VAR
-	done
-	sleep 2
+		echo "-- Deleting other variables"
+		OTHER_MESSAGES=(save_lang chat_msg_long chat_msg_lines pwd_cannot pwd_can pwd_min pwd_success pwd_set_error pwd_setup ip nick user host ip_range because op type not_in_userlist error success wrong_dc_tag tag_max_hubs tag_max_slots tag_min_slots tag_max_hs_ratio tag_min_limit tag_min_ls_ratio tag_no_sock msg_downgrade msg_upgrade msg_topic_set msg_topic_reset autoreg_nick_prefix autoreg_already_reg autoreg_success autoreg_error timeout_any operation_timeout msg_chat_onoff msg_change_pwd msg_banned msg_hub_full msg_nick_prefix msg_downgrade msg_upgrade msg_replace_ban login_share_min login_share_max autoreg_min_share search_share_min ctm_share_min max_attempts_threshold)
+		for VAR in ${OTHER_MESSAGES[@]}; do
+			_delete_lang_var $VAR
+		done
+		sleep 2
 
-	echo "-- Copying new help file for commands"
-	if ! cp $DATADIR/config/help_* $CHOOSEN_FOLDER 	; then
-		echo_s "-- Error copying help_* files from $DATADIR\n" $RED
-	fi
+		echo "-- Copying new help file for commands"
+		if ! cp $DATADIR/config/help_* $CHOOSEN_FOLDER 	; then
+			echo_s "-- Error copying help_* files from $DATADIR\n" $RED
+		fi
 
-	QUERY='TRUNCATE TABLE pi_plug';
-	echo "-- Truncating pi_plug table; it will updated with verlihub"
-	if ! _mysql_query "$QUERY" ; then
-		echo_s "-- Error truncating 'pi_plugin' table; make it manually using '$QUERY'\n" $RED
-	fi
+		QUERY='TRUNCATE TABLE pi_plug';
+		echo "-- Truncating pi_plug table; it will updated with verlihub"
+		if ! _mysql_query "$QUERY" ; then
+			echo_s "-- Error truncating 'pi_plugin' table; make it manually using '$QUERY'\n" $RED
+		fi
 	
-	echo "-- Renaming variable 'lang_name' to 'locale' in dbconfig file"
-	sed -i "s/lang_name/locale/g" "$CONFIG_DIR/dbconfig"  > /dev/null 2>&1
+		echo "-- Renaming variable 'lang_name' to 'locale' in dbconfig file"
+		sed -i "s/lang_name/locale/g" "$CONFIG_DIR/dbconfig" > /dev/null 2>&1
 
-	echo "-- Done. Restart VerliHub now."
-else
-	echo "-- Skipped migration"
-fi
+		echo "-- Done. Restart VerliHub now."
+	else
+		echo "-- Skipped migration"
+	fi
+	exit 0;
+}
+
+function migrate_clean()
+{
+	if [ $UID -ne 0 ]; then
+		echo_s "-- You can run this migration with root account only\n" $RED
+		exit 0;
+	fi
+	echo_s "-- Welcome to VerliHub migration script to version 0.9.9a to clean up old files\n" $RED_BOLD
+	if $(yes_or_no "Do you want to continue with hub migration?") ; then
+		OLD_SCRIPTS=(vh_getcfg vh_getdb vh_install vh_regnick vh_restart vh_runhub vh_setup vh_trigger)
+
+		for VAR in ${OLD_SCRIPTS[@]}; do
+			FILE="$BINDIR/$VAR"
+			echo -n "-- Searching $FILE"
+			sleep 1
+			if [ -f $FILE ]; then
+				if rm -f $FILE > /dev/null 2>&1 ; then
+					echo ". Deleted"
+				else
+					echo ". Error, remove '$FILE' manually"
+				fi
+			else
+				echo ". Not found"
+			fi
+		done
+		echo "-- Done."
+	else
+		echo "-- Skipped migration"
+	fi
+	exit 0;
+}
+
+case "_$1" in
+	"_") 		help_me ;;
+	"_--help") 	help_me;;
+	"_--clean") migrate_clean;;
+	"_--hub")	shift && migrate_hub $@;;
+	*)
+		echo_s "Unknown option $1, try $SCRIPT --help\n" $RED
+		exit;;
+esac;
 exit 0;
